apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pr-7780
#namePrefix: preview-
#nameSuffix: 
commonLabels:
  customer: preview
resources:
# - mysql-sec.yaml
# - ../../../base/apps/mysql
#- mysql-cm.yaml
#- my-sql-sec.yaml
- ../../../../../base/apps/moco-mysql
- be-sec.yaml
- be-cm.yaml
- be-ingress.yaml
- ../../../../../base/apps/be
- fe-cm.yaml
- fe-sec.yaml
- fe-ingress.yaml
- ../../../../../base/apps/fe

patchesStrategicMerge:
# - mysql-deploy-cluster.yaml
# - my-sql-deployment.yaml
- be-deploy.yaml
- fe-deploy.yaml

images:
- name: 389132740677.dkr.ecr.us-east-1.amazonaws.com/laravel-preview-backend
  newTag: c1149db4b3f513a9896b472ec7f23af7e8a143e2
- name: 389132740677.dkr.ecr.us-east-1.amazonaws.com/fume-preview-frontend
  newTag: c1149db4b3f513a9896b472ec7f23af7e8a143e2
