apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  type: ClusterIP
  ports:
  - name: http-laravel
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: laravel