---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-sql-pv-volume-preview-pr-7974
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
