---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sql-pv-claim-preview-pr-7974
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
