---
apiVersion: v1
kind: Service
metadata:
  name: my-sql
  labels:
    app: my-sql
spec:
  type: ClusterIP
  ports:
  - name: http-my-sql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: my-sql
                
