apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pr-8205
#namePrefix: preview-
#nameSuffix: 
commonLabels:
  customer: preview
resources:
# - mysql-sec.yaml
# - ../../../base/apps/mysql
#- mysql-cm.yaml
#- my-sql-sec.yaml
- ../../../../../base/apps/moco-mysql
- be-sec.yaml
- be-cm.yaml
- be-ingress.yaml
- ../../../../../base/apps/be
- fe-cm.yaml
- fe-sec.yaml
- fe-ingress.yaml
- ../../../../../base/apps/fe

patchesStrategicMerge:
# - mysql-deploy-cluster.yaml
# - my-sql-deployment.yaml
- be-deploy.yaml
- fe-deploy.yaml

images:
- name: image_url/laravel-preview-backend
  newTag: 1a356d8e40cb4471f9eff0d6df33ad0aae8a7c96
- name: image_url/fume-preview-frontend
  newTag: 1a356d8e40cb4471f9eff0d6df33ad0aae8a7c96
