apiVersion: apps/v1
kind: Deployment
metadata:
  name: fume
  labels:
    app: fume
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: fume
  template:
    metadata:
      labels:
        app: fume
    spec:
      containers:
        - name: fume
          image: image_url/fume-preview-frontend       
          envFrom:
            - configMapRef:
                name: fume-env-cm
            - secretRef:
                name: fume-env-sec
          ports:
            - containerPort: 3000
              name: http-fume
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 10            
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "1024Mi"
